server:
  port: 8091

spring:

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:payment-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: create-drop #toda vez que rodar destrói e cria do zero
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect