server:
  port: 8090

spring:
  kafka:
    bootstrap-servers: ${KAFKA_BROKER:localhost:9092}
    topic:
      orchestrator: orchestrator
      produto-validacao-sucesso: produtos-validacao-sucesso
      produto-validacao-falha: produtos-validacao-falha
    consumer:
      group-id: product-validation-group
      auto-offset-reset: latest

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:product-db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate.ddl-auto: create-drop #toda vez que rodar destrói e cria do zero
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org:
      apache:
        kafka: OFF